# Generated by Django 3.2.8 on 2021-10-10 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Name')),
                ('price', models.FloatField(max_length=4, verbose_name='Price')),
                ('description', models.TextField(verbose_name='Description')),
            ],
        ),
    ]
